services:
  - type: web
    name: rms-backend
    runtime: docker
    repo: https://github.com/nurinsolehah/rms-backend.git
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - "*/"
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
